###
## Expected result is ........
GET http://localhost:3000/api/v1/gradeHistories?filter={"class_id":1} HTTP/3.0

###

## Expected result is ........
GET http://localhost:3000/api/v1/gradeHistories?filter={"scores": {"$elemMatch": {"type": "homework", "score": { "$gt": 99 }}}} HTTP/3.0


