
@path = api/v1/users
@endpoint = http://localhost:3000/api/v1/users

###
### POST Request for a user 
## Expected result is ........

# @name  postAUser
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "name" : "Monday is here",
   "email": "jdoe123@gmail.com",
   "status": "pending"
}

###
@newObjectID = {{postAUser.response.headers.location}}

GET {{endpoint}}/{{newObjectID}}

###
POST {{endpoint}} HTTP/3.0
content-type: application/json

{ "name" : "Checking Date",
   "email": "jdoe123@gmail.com"
}

###
PUT {{endpoint}}/{{firstID}}
content-type: application/json

{ "name" : "goodbye again",
   "phonenumber" : "0871234567",
   "email": "jdoe123@gmail.com"}


###
GET {{endpoint}}/66f2956d53ce2ac5467af205

###
DELETE http://localhost:3000/api/v1/users/66f2956d53ce2ac5467af205 HTTP/1.1
content-type: application/json


###
# @name GETAllUsers
GET {{endpoint}}

@firstID = {{GETAllUsers.response.body.$[0]._id}}


###
GET {{endpoint}}/{{firstID}} HTTP/1.1
